// Code generated by protoc-gen-go.
// source: src/protos/db/db.proto
// DO NOT EDIT!

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	src/protos/db/db.proto

It has these top-level messages:
	DB_UpdateLastLoginTime
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type DB_UpdateLastLoginTime struct {
	UserID           *uint64 `protobuf:"varint,1,req,name=UserID,json=userID" json:"UserID,omitempty"`
	Time             *int64  `protobuf:"varint,2,req,name=Time,json=time" json:"Time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DB_UpdateLastLoginTime) Reset()                    { *m = DB_UpdateLastLoginTime{} }
func (m *DB_UpdateLastLoginTime) String() string            { return proto.CompactTextString(m) }
func (*DB_UpdateLastLoginTime) ProtoMessage()               {}
func (*DB_UpdateLastLoginTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DB_UpdateLastLoginTime) GetUserID() uint64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *DB_UpdateLastLoginTime) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*DB_UpdateLastLoginTime)(nil), "DB_UpdateLastLoginTime")
}

var fileDescriptor0 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x2e, 0x4a, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0xd6, 0x4f, 0x49, 0x02, 0x22, 0x3d, 0x30, 0x47, 0xc9, 0x85,
	0x4b, 0xcc, 0xc5, 0x29, 0x3e, 0xb4, 0x20, 0x25, 0xb1, 0x24, 0xd5, 0x27, 0xb1, 0xb8, 0xc4, 0x27,
	0x3f, 0x3d, 0x33, 0x2f, 0x24, 0x33, 0x37, 0x55, 0x48, 0x8c, 0x8b, 0x2d, 0xb4, 0x38, 0xb5, 0xc8,
	0xd3, 0x45, 0x82, 0x51, 0x81, 0x49, 0x83, 0x25, 0x88, 0xad, 0x14, 0xcc, 0x13, 0x12, 0xe2, 0x62,
	0x01, 0xc9, 0x4b, 0x30, 0x01, 0x45, 0x99, 0x83, 0x58, 0x4a, 0x80, 0x6c, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x34, 0xba, 0x5b, 0x9a, 0x5e, 0x00, 0x00, 0x00,
}
