// Code generated by protoc-gen-go.
// source: src/protos/config/config.proto
// DO NOT EDIT!

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	src/protos/config/config.proto

It has these top-level messages:
	FBInfo
	FBInfoList
	ItemInfo
	ItemInfoList
	ItemGroupInfo
	ItemGroupInfoList
	MonsterInfo
	MonsterInfoList
	MonsterGroupInfo
	MonsterGroupInfoList
	SkillInfo
	SkillInfoList
	GlobalConfigInfo
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type FBInfo struct {
	ID               *int64  `protobuf:"varint,1,req,name=ID,json=iD" json:"ID,omitempty"`
	FBID             *int64  `protobuf:"varint,2,req,name=FBID,json=fBID" json:"FBID,omitempty"`
	FBName           *string `protobuf:"bytes,3,req,name=FBName,json=fBName" json:"FBName,omitempty"`
	FBDesc           *string `protobuf:"bytes,4,req,name=FBDesc,json=fBDesc" json:"FBDesc,omitempty"`
	MonsterGroupID   *string `protobuf:"bytes,5,req,name=MonsterGroupID,json=monsterGroupID" json:"MonsterGroupID,omitempty"`
	ItemGroupID      *string `protobuf:"bytes,6,req,name=ItemGroupID,json=itemGroupID" json:"ItemGroupID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FBInfo) Reset()                    { *m = FBInfo{} }
func (m *FBInfo) String() string            { return proto.CompactTextString(m) }
func (*FBInfo) ProtoMessage()               {}
func (*FBInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FBInfo) GetID() int64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *FBInfo) GetFBID() int64 {
	if m != nil && m.FBID != nil {
		return *m.FBID
	}
	return 0
}

func (m *FBInfo) GetFBName() string {
	if m != nil && m.FBName != nil {
		return *m.FBName
	}
	return ""
}

func (m *FBInfo) GetFBDesc() string {
	if m != nil && m.FBDesc != nil {
		return *m.FBDesc
	}
	return ""
}

func (m *FBInfo) GetMonsterGroupID() string {
	if m != nil && m.MonsterGroupID != nil {
		return *m.MonsterGroupID
	}
	return ""
}

func (m *FBInfo) GetItemGroupID() string {
	if m != nil && m.ItemGroupID != nil {
		return *m.ItemGroupID
	}
	return ""
}

type FBInfoList struct {
	FbList           []*FBInfo `protobuf:"bytes,1,rep,name=fbList" json:"fbList,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *FBInfoList) Reset()                    { *m = FBInfoList{} }
func (m *FBInfoList) String() string            { return proto.CompactTextString(m) }
func (*FBInfoList) ProtoMessage()               {}
func (*FBInfoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FBInfoList) GetFbList() []*FBInfo {
	if m != nil {
		return m.FbList
	}
	return nil
}

type ItemInfo struct {
	ID               *int64  `protobuf:"varint,1,req,name=ID,json=iD" json:"ID,omitempty"`
	ItemID           *int64  `protobuf:"varint,2,req,name=ItemID,json=itemID" json:"ItemID,omitempty"`
	ItemName         *string `protobuf:"bytes,3,req,name=ItemName,json=itemName" json:"ItemName,omitempty"`
	ItemDesc         *string `protobuf:"bytes,4,req,name=ItemDesc,json=itemDesc" json:"ItemDesc,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ItemInfo) Reset()                    { *m = ItemInfo{} }
func (m *ItemInfo) String() string            { return proto.CompactTextString(m) }
func (*ItemInfo) ProtoMessage()               {}
func (*ItemInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ItemInfo) GetID() int64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *ItemInfo) GetItemID() int64 {
	if m != nil && m.ItemID != nil {
		return *m.ItemID
	}
	return 0
}

func (m *ItemInfo) GetItemName() string {
	if m != nil && m.ItemName != nil {
		return *m.ItemName
	}
	return ""
}

func (m *ItemInfo) GetItemDesc() string {
	if m != nil && m.ItemDesc != nil {
		return *m.ItemDesc
	}
	return ""
}

type ItemInfoList struct {
	ItemList         []*ItemInfo `protobuf:"bytes,1,rep,name=itemList" json:"itemList,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ItemInfoList) Reset()                    { *m = ItemInfoList{} }
func (m *ItemInfoList) String() string            { return proto.CompactTextString(m) }
func (*ItemInfoList) ProtoMessage()               {}
func (*ItemInfoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ItemInfoList) GetItemList() []*ItemInfo {
	if m != nil {
		return m.ItemList
	}
	return nil
}

type ItemGroupInfo struct {
	ID               *int64  `protobuf:"varint,1,req,name=ID,json=iD" json:"ID,omitempty"`
	ItemGroupID      *int64  `protobuf:"varint,2,req,name=ItemGroupID,json=itemGroupID" json:"ItemGroupID,omitempty"`
	ItemGroupName    *string `protobuf:"bytes,3,req,name=ItemGroupName,json=itemGroupName" json:"ItemGroupName,omitempty"`
	ItemGroupData    *string `protobuf:"bytes,4,req,name=ItemGroupData,json=itemGroupData" json:"ItemGroupData,omitempty"`
	ItemGroupDesc    *string `protobuf:"bytes,5,req,name=ItemGroupDesc,json=itemGroupDesc" json:"ItemGroupDesc,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ItemGroupInfo) Reset()                    { *m = ItemGroupInfo{} }
func (m *ItemGroupInfo) String() string            { return proto.CompactTextString(m) }
func (*ItemGroupInfo) ProtoMessage()               {}
func (*ItemGroupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ItemGroupInfo) GetID() int64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *ItemGroupInfo) GetItemGroupID() int64 {
	if m != nil && m.ItemGroupID != nil {
		return *m.ItemGroupID
	}
	return 0
}

func (m *ItemGroupInfo) GetItemGroupName() string {
	if m != nil && m.ItemGroupName != nil {
		return *m.ItemGroupName
	}
	return ""
}

func (m *ItemGroupInfo) GetItemGroupData() string {
	if m != nil && m.ItemGroupData != nil {
		return *m.ItemGroupData
	}
	return ""
}

func (m *ItemGroupInfo) GetItemGroupDesc() string {
	if m != nil && m.ItemGroupDesc != nil {
		return *m.ItemGroupDesc
	}
	return ""
}

type ItemGroupInfoList struct {
	ItemGroupList    []*ItemGroupInfo `protobuf:"bytes,1,rep,name=itemGroupList" json:"itemGroupList,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ItemGroupInfoList) Reset()                    { *m = ItemGroupInfoList{} }
func (m *ItemGroupInfoList) String() string            { return proto.CompactTextString(m) }
func (*ItemGroupInfoList) ProtoMessage()               {}
func (*ItemGroupInfoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ItemGroupInfoList) GetItemGroupList() []*ItemGroupInfo {
	if m != nil {
		return m.ItemGroupList
	}
	return nil
}

type MonsterInfo struct {
	ID               *int64  `protobuf:"varint,1,req,name=ID,json=iD" json:"ID,omitempty"`
	MonsterID        *int64  `protobuf:"varint,2,req,name=MonsterID,json=monsterID" json:"MonsterID,omitempty"`
	MonsterName      *string `protobuf:"bytes,3,req,name=MonsterName,json=monsterName" json:"MonsterName,omitempty"`
	MonsterDesc      *string `protobuf:"bytes,4,req,name=MonsterDesc,json=monsterDesc" json:"MonsterDesc,omitempty"`
	HP               *int64  `protobuf:"varint,5,req,name=HP,json=hP" json:"HP,omitempty"`
	MP               *int64  `protobuf:"varint,6,req,name=MP,json=mP" json:"MP,omitempty"`
	Strength         *int64  `protobuf:"varint,7,req,name=Strength,json=strength" json:"Strength,omitempty"`
	Agility          *int64  `protobuf:"varint,8,req,name=Agility,json=agility" json:"Agility,omitempty"`
	PhysicalAttack   *int64  `protobuf:"varint,9,req,name=PhysicalAttack,json=physicalAttack" json:"PhysicalAttack,omitempty"`
	PhysicalDefense  *int64  `protobuf:"varint,10,req,name=PhysicalDefense,json=physicalDefense" json:"PhysicalDefense,omitempty"`
	MagicAttack      *int64  `protobuf:"varint,11,req,name=MagicAttack,json=magicAttack" json:"MagicAttack,omitempty"`
	MagicDefense     *int64  `protobuf:"varint,12,req,name=MagicDefense,json=magicDefense" json:"MagicDefense,omitempty"`
	Skill_1          *int64  `protobuf:"varint,13,opt,name=Skill_1,json=skill1" json:"Skill_1,omitempty"`
	Skill_2          *int64  `protobuf:"varint,14,opt,name=Skill_2,json=skill2" json:"Skill_2,omitempty"`
	Skill_3          *int64  `protobuf:"varint,15,opt,name=Skill_3,json=skill3" json:"Skill_3,omitempty"`
	Skill_4          *int64  `protobuf:"varint,16,opt,name=Skill_4,json=skill4" json:"Skill_4,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MonsterInfo) Reset()                    { *m = MonsterInfo{} }
func (m *MonsterInfo) String() string            { return proto.CompactTextString(m) }
func (*MonsterInfo) ProtoMessage()               {}
func (*MonsterInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MonsterInfo) GetID() int64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *MonsterInfo) GetMonsterID() int64 {
	if m != nil && m.MonsterID != nil {
		return *m.MonsterID
	}
	return 0
}

func (m *MonsterInfo) GetMonsterName() string {
	if m != nil && m.MonsterName != nil {
		return *m.MonsterName
	}
	return ""
}

func (m *MonsterInfo) GetMonsterDesc() string {
	if m != nil && m.MonsterDesc != nil {
		return *m.MonsterDesc
	}
	return ""
}

func (m *MonsterInfo) GetHP() int64 {
	if m != nil && m.HP != nil {
		return *m.HP
	}
	return 0
}

func (m *MonsterInfo) GetMP() int64 {
	if m != nil && m.MP != nil {
		return *m.MP
	}
	return 0
}

func (m *MonsterInfo) GetStrength() int64 {
	if m != nil && m.Strength != nil {
		return *m.Strength
	}
	return 0
}

func (m *MonsterInfo) GetAgility() int64 {
	if m != nil && m.Agility != nil {
		return *m.Agility
	}
	return 0
}

func (m *MonsterInfo) GetPhysicalAttack() int64 {
	if m != nil && m.PhysicalAttack != nil {
		return *m.PhysicalAttack
	}
	return 0
}

func (m *MonsterInfo) GetPhysicalDefense() int64 {
	if m != nil && m.PhysicalDefense != nil {
		return *m.PhysicalDefense
	}
	return 0
}

func (m *MonsterInfo) GetMagicAttack() int64 {
	if m != nil && m.MagicAttack != nil {
		return *m.MagicAttack
	}
	return 0
}

func (m *MonsterInfo) GetMagicDefense() int64 {
	if m != nil && m.MagicDefense != nil {
		return *m.MagicDefense
	}
	return 0
}

func (m *MonsterInfo) GetSkill_1() int64 {
	if m != nil && m.Skill_1 != nil {
		return *m.Skill_1
	}
	return 0
}

func (m *MonsterInfo) GetSkill_2() int64 {
	if m != nil && m.Skill_2 != nil {
		return *m.Skill_2
	}
	return 0
}

func (m *MonsterInfo) GetSkill_3() int64 {
	if m != nil && m.Skill_3 != nil {
		return *m.Skill_3
	}
	return 0
}

func (m *MonsterInfo) GetSkill_4() int64 {
	if m != nil && m.Skill_4 != nil {
		return *m.Skill_4
	}
	return 0
}

type MonsterInfoList struct {
	MonsterList      []*MonsterInfo `protobuf:"bytes,1,rep,name=monsterList" json:"monsterList,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *MonsterInfoList) Reset()                    { *m = MonsterInfoList{} }
func (m *MonsterInfoList) String() string            { return proto.CompactTextString(m) }
func (*MonsterInfoList) ProtoMessage()               {}
func (*MonsterInfoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MonsterInfoList) GetMonsterList() []*MonsterInfo {
	if m != nil {
		return m.MonsterList
	}
	return nil
}

type MonsterGroupInfo struct {
	ID               *int64  `protobuf:"varint,1,req,name=ID,json=iD" json:"ID,omitempty"`
	MonsterGroupID   *int64  `protobuf:"varint,2,req,name=MonsterGroupID,json=monsterGroupID" json:"MonsterGroupID,omitempty"`
	MonsterGroupName *string `protobuf:"bytes,3,req,name=MonsterGroupName,json=monsterGroupName" json:"MonsterGroupName,omitempty"`
	MonsterGroupData *string `protobuf:"bytes,4,req,name=MonsterGroupData,json=monsterGroupData" json:"MonsterGroupData,omitempty"`
	MonsterGroupDesc *string `protobuf:"bytes,5,req,name=MonsterGroupDesc,json=monsterGroupDesc" json:"MonsterGroupDesc,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MonsterGroupInfo) Reset()                    { *m = MonsterGroupInfo{} }
func (m *MonsterGroupInfo) String() string            { return proto.CompactTextString(m) }
func (*MonsterGroupInfo) ProtoMessage()               {}
func (*MonsterGroupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MonsterGroupInfo) GetID() int64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *MonsterGroupInfo) GetMonsterGroupID() int64 {
	if m != nil && m.MonsterGroupID != nil {
		return *m.MonsterGroupID
	}
	return 0
}

func (m *MonsterGroupInfo) GetMonsterGroupName() string {
	if m != nil && m.MonsterGroupName != nil {
		return *m.MonsterGroupName
	}
	return ""
}

func (m *MonsterGroupInfo) GetMonsterGroupData() string {
	if m != nil && m.MonsterGroupData != nil {
		return *m.MonsterGroupData
	}
	return ""
}

func (m *MonsterGroupInfo) GetMonsterGroupDesc() string {
	if m != nil && m.MonsterGroupDesc != nil {
		return *m.MonsterGroupDesc
	}
	return ""
}

type MonsterGroupInfoList struct {
	MonsterGroupList []*MonsterGroupInfo `protobuf:"bytes,1,rep,name=monsterGroupList" json:"monsterGroupList,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *MonsterGroupInfoList) Reset()                    { *m = MonsterGroupInfoList{} }
func (m *MonsterGroupInfoList) String() string            { return proto.CompactTextString(m) }
func (*MonsterGroupInfoList) ProtoMessage()               {}
func (*MonsterGroupInfoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MonsterGroupInfoList) GetMonsterGroupList() []*MonsterGroupInfo {
	if m != nil {
		return m.MonsterGroupList
	}
	return nil
}

type SkillInfo struct {
	ID               *int64  `protobuf:"varint,1,req,name=ID,json=iD" json:"ID,omitempty"`
	SkillID          *int64  `protobuf:"varint,2,req,name=SkillID,json=skillID" json:"SkillID,omitempty"`
	SkillName        *string `protobuf:"bytes,3,req,name=SkillName,json=skillName" json:"SkillName,omitempty"`
	SkillDesc        *string `protobuf:"bytes,4,req,name=SkillDesc,json=skillDesc" json:"SkillDesc,omitempty"`
	SkillEffect      *string `protobuf:"bytes,5,req,name=SkillEffect,json=skillEffect" json:"SkillEffect,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SkillInfo) Reset()                    { *m = SkillInfo{} }
func (m *SkillInfo) String() string            { return proto.CompactTextString(m) }
func (*SkillInfo) ProtoMessage()               {}
func (*SkillInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SkillInfo) GetID() int64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *SkillInfo) GetSkillID() int64 {
	if m != nil && m.SkillID != nil {
		return *m.SkillID
	}
	return 0
}

func (m *SkillInfo) GetSkillName() string {
	if m != nil && m.SkillName != nil {
		return *m.SkillName
	}
	return ""
}

func (m *SkillInfo) GetSkillDesc() string {
	if m != nil && m.SkillDesc != nil {
		return *m.SkillDesc
	}
	return ""
}

func (m *SkillInfo) GetSkillEffect() string {
	if m != nil && m.SkillEffect != nil {
		return *m.SkillEffect
	}
	return ""
}

type SkillInfoList struct {
	SkillList        []*SkillInfo `protobuf:"bytes,1,rep,name=skillList" json:"skillList,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SkillInfoList) Reset()                    { *m = SkillInfoList{} }
func (m *SkillInfoList) String() string            { return proto.CompactTextString(m) }
func (*SkillInfoList) ProtoMessage()               {}
func (*SkillInfoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SkillInfoList) GetSkillList() []*SkillInfo {
	if m != nil {
		return m.SkillList
	}
	return nil
}

type GlobalConfigInfo struct {
	FbInfoList           *FBInfoList           `protobuf:"bytes,1,req,name=fbInfoList" json:"fbInfoList,omitempty"`
	ItemInfoList         *ItemInfoList         `protobuf:"bytes,2,req,name=itemInfoList" json:"itemInfoList,omitempty"`
	ItemGroupInfoList    *ItemGroupInfoList    `protobuf:"bytes,3,req,name=itemGroupInfoList" json:"itemGroupInfoList,omitempty"`
	SkillInfoList        *SkillInfoList        `protobuf:"bytes,4,req,name=skillInfoList" json:"skillInfoList,omitempty"`
	MonsterInfoList      *MonsterInfoList      `protobuf:"bytes,5,req,name=monsterInfoList" json:"monsterInfoList,omitempty"`
	MonsterGroupInfoList *MonsterGroupInfoList `protobuf:"bytes,6,req,name=monsterGroupInfoList" json:"monsterGroupInfoList,omitempty"`
	XXX_unrecognized     []byte                `json:"-"`
}

func (m *GlobalConfigInfo) Reset()                    { *m = GlobalConfigInfo{} }
func (m *GlobalConfigInfo) String() string            { return proto.CompactTextString(m) }
func (*GlobalConfigInfo) ProtoMessage()               {}
func (*GlobalConfigInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GlobalConfigInfo) GetFbInfoList() *FBInfoList {
	if m != nil {
		return m.FbInfoList
	}
	return nil
}

func (m *GlobalConfigInfo) GetItemInfoList() *ItemInfoList {
	if m != nil {
		return m.ItemInfoList
	}
	return nil
}

func (m *GlobalConfigInfo) GetItemGroupInfoList() *ItemGroupInfoList {
	if m != nil {
		return m.ItemGroupInfoList
	}
	return nil
}

func (m *GlobalConfigInfo) GetSkillInfoList() *SkillInfoList {
	if m != nil {
		return m.SkillInfoList
	}
	return nil
}

func (m *GlobalConfigInfo) GetMonsterInfoList() *MonsterInfoList {
	if m != nil {
		return m.MonsterInfoList
	}
	return nil
}

func (m *GlobalConfigInfo) GetMonsterGroupInfoList() *MonsterGroupInfoList {
	if m != nil {
		return m.MonsterGroupInfoList
	}
	return nil
}

func init() {
	proto.RegisterType((*FBInfo)(nil), "FBInfo")
	proto.RegisterType((*FBInfoList)(nil), "FBInfoList")
	proto.RegisterType((*ItemInfo)(nil), "ItemInfo")
	proto.RegisterType((*ItemInfoList)(nil), "ItemInfoList")
	proto.RegisterType((*ItemGroupInfo)(nil), "ItemGroupInfo")
	proto.RegisterType((*ItemGroupInfoList)(nil), "ItemGroupInfoList")
	proto.RegisterType((*MonsterInfo)(nil), "MonsterInfo")
	proto.RegisterType((*MonsterInfoList)(nil), "MonsterInfoList")
	proto.RegisterType((*MonsterGroupInfo)(nil), "MonsterGroupInfo")
	proto.RegisterType((*MonsterGroupInfoList)(nil), "MonsterGroupInfoList")
	proto.RegisterType((*SkillInfo)(nil), "SkillInfo")
	proto.RegisterType((*SkillInfoList)(nil), "SkillInfoList")
	proto.RegisterType((*GlobalConfigInfo)(nil), "GlobalConfigInfo")
}

var fileDescriptor0 = []byte{
	// 756 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x55, 0x5d, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0x92, 0x36, 0x3f, 0xe3, 0xfc, 0x75, 0x55, 0x60, 0x85, 0x10, 0x54, 0x16, 0xa0, 0x08,
	0x84, 0xab, 0xba, 0xe5, 0x01, 0x24, 0x24, 0x0a, 0x81, 0x12, 0x89, 0xa2, 0x68, 0x2b, 0x9e, 0x91,
	0x6b, 0xd9, 0xad, 0x69, 0x1c, 0x47, 0xb1, 0x79, 0xe8, 0x39, 0xb8, 0x03, 0x17, 0xe0, 0x1e, 0x48,
	0x1c, 0x85, 0x1b, 0xe0, 0x1d, 0x7b, 0xb3, 0xb3, 0x8e, 0x9f, 0x92, 0xf9, 0xbe, 0xcf, 0xeb, 0xf9,
	0x66, 0x67, 0xc6, 0xf0, 0x30, 0x5d, 0xfb, 0x87, 0xab, 0x75, 0x92, 0x25, 0xe9, 0xa1, 0x9f, 0x2c,
	0xc3, 0xe8, 0xaa, 0xfc, 0x71, 0x10, 0xb4, 0x7f, 0x35, 0xa0, 0xfd, 0xf1, 0xdd, 0x6c, 0x19, 0x26,
	0x6c, 0x08, 0xcd, 0xd9, 0x94, 0x37, 0x0e, 0x9a, 0x93, 0x96, 0x68, 0x46, 0x53, 0xc6, 0x60, 0x27,
	0x67, 0xa6, 0xbc, 0x89, 0xc8, 0x4e, 0x98, 0xff, 0x67, 0x77, 0xa5, 0xfa, 0x8b, 0x17, 0x07, 0xbc,
	0x95, 0xa3, 0x3d, 0xd1, 0x0e, 0x31, 0x2a, 0xf0, 0x69, 0x90, 0xfa, 0x7c, 0x47, 0xe1, 0x32, 0x62,
	0x4f, 0x61, 0x78, 0x9e, 0x2c, 0xd3, 0x2c, 0x58, 0x9f, 0xad, 0x93, 0x1f, 0xab, 0xfc, 0xb4, 0x5d,
	0xe4, 0x87, 0xb1, 0x81, 0xb2, 0x03, 0xb0, 0x66, 0x59, 0x10, 0x2b, 0x51, 0x1b, 0x45, 0x56, 0xa4,
	0x21, 0xfb, 0x05, 0x40, 0x91, 0xe7, 0xe7, 0x28, 0xcd, 0xd8, 0x23, 0x68, 0x87, 0x97, 0xf2, 0x5f,
	0x9e, 0x6f, 0x6b, 0x62, 0xb9, 0x1d, 0xa7, 0x20, 0x45, 0x09, 0xdb, 0xdf, 0xa1, 0x2b, 0x0f, 0xac,
	0x35, 0x96, 0x27, 0x8b, 0x9c, 0xb2, 0xd6, 0x8e, 0x30, 0x62, 0xf7, 0x8b, 0x67, 0x88, 0xbd, 0x6e,
	0x54, 0xc6, 0x8a, 0x23, 0x16, 0x91, 0x93, 0xb1, 0xfd, 0x12, 0xfa, 0xea, 0x5d, 0x98, 0xdc, 0x13,
	0x40, 0x8e, 0xa4, 0xd7, 0x73, 0x94, 0x40, 0x6c, 0x28, 0xfb, 0x77, 0x03, 0x06, 0xda, 0x74, 0x5d,
	0xa2, 0x95, 0xaa, 0x14, 0xd9, 0xd2, 0xaa, 0xb0, 0xc7, 0xe4, 0x08, 0x92, 0xf7, 0x20, 0xa2, 0xa0,
	0xa1, 0x9a, 0x7a, 0x99, 0x57, 0x3a, 0xd0, 0x2a, 0x09, 0x9a, 0x2a, 0xe9, 0x73, 0xb7, 0xaa, 0x92,
	0x66, 0x67, 0xb0, 0x67, 0x24, 0x8d, 0x8e, 0x4f, 0x40, 0xab, 0x88, 0xed, 0xa1, 0x63, 0x48, 0x85,
	0x29, 0xb2, 0xff, 0xb6, 0xc0, 0x2a, 0xbb, 0xa3, 0xd6, 0xfe, 0x03, 0xe8, 0x29, 0x5a, 0x99, 0xef,
	0xc5, 0x0a, 0x90, 0xc5, 0x29, 0x59, 0x62, 0xdc, 0x8a, 0x35, 0x44, 0x14, 0xe4, 0xda, 0x94, 0x02,
	0xdb, 0x33, 0x7f, 0xe3, 0xa7, 0x39, 0xfa, 0xcc, 0xdf, 0x78, 0x3d, 0x97, 0xf1, 0xf9, 0x1c, 0xbb,
	0x2f, 0x8f, 0xe3, 0xb9, 0xbc, 0xf5, 0x8b, 0x6c, 0x1d, 0x2c, 0xaf, 0xb2, 0x6b, 0xde, 0x41, 0xb4,
	0x9b, 0x96, 0x31, 0xe3, 0xd0, 0x39, 0xbd, 0x8a, 0x16, 0x51, 0x76, 0xcb, 0xbb, 0x48, 0x75, 0xbc,
	0x22, 0x94, 0x4d, 0x3f, 0xbf, 0xbe, 0x4d, 0x23, 0xdf, 0x5b, 0x9c, 0x66, 0x99, 0xe7, 0xdf, 0xf0,
	0x1e, 0x0a, 0x86, 0x2b, 0x03, 0x65, 0x13, 0x18, 0x29, 0xdd, 0x34, 0x08, 0x83, 0x65, 0x1a, 0x70,
	0x40, 0xe1, 0x68, 0x65, 0xc2, 0xe8, 0x24, 0x3f, 0xdd, 0x2f, 0x8f, 0xb3, 0x8a, 0x46, 0x88, 0x35,
	0xc4, 0x6c, 0xe8, 0xa3, 0x42, 0x1d, 0xd4, 0x47, 0x49, 0x3f, 0x26, 0x18, 0xbb, 0x07, 0x9d, 0x8b,
	0x9b, 0x68, 0xb1, 0xf8, 0x76, 0xc4, 0x07, 0x07, 0x0d, 0xd9, 0xf8, 0xa9, 0x0c, 0x8f, 0x34, 0xe1,
	0xf2, 0x21, 0x21, 0x5c, 0x4d, 0x1c, 0xf3, 0x11, 0x21, 0x8e, 0x35, 0x71, 0xc2, 0xc7, 0x84, 0x38,
	0xb1, 0x4f, 0x61, 0x44, 0xae, 0x14, 0x9b, 0xc3, 0x01, 0x55, 0x73, 0xd2, 0x1a, 0x7d, 0x87, 0xc8,
	0x04, 0x15, 0xd8, 0x7f, 0x1a, 0x30, 0x36, 0x96, 0x46, 0x5d, 0x6f, 0x6c, 0x2f, 0x96, 0xa2, 0x41,
	0xaa, 0x8b, 0xe5, 0x99, 0x79, 0x16, 0x69, 0x95, 0x71, 0x5c, 0xc1, 0xab, 0x5a, 0x32, 0x29, 0x86,
	0x16, 0x87, 0xa5, 0xaa, 0xd5, 0xf3, 0x62, 0x6a, 0xe5, 0xc8, 0x7c, 0x85, 0xfd, 0xaa, 0x1f, 0x2c,
	0xcc, 0x1b, 0x30, 0xb4, 0xa4, 0x3a, 0x7b, 0x4e, 0xf5, 0x01, 0xb1, 0x25, 0xb5, 0x7f, 0x36, 0xa0,
	0x87, 0x97, 0x50, 0x5b, 0x20, 0x5e, 0xde, 0xd0, 0xa6, 0x32, 0x9d, 0xb4, 0x08, 0xe5, 0x58, 0x21,
	0x43, 0x6a, 0xd1, 0x4b, 0x15, 0xb0, 0x61, 0xc9, 0xc8, 0x14, 0x2c, 0x0e, 0x4c, 0xde, 0x88, 0xc8,
	0x7e, 0x08, 0xc3, 0xc0, 0xcf, 0x4a, 0xc7, 0x56, 0xaa, 0x21, 0xfb, 0x15, 0x0c, 0x36, 0x49, 0xa1,
	0xcb, 0x09, 0x14, 0xcf, 0x13, 0x7b, 0xe0, 0x6c, 0x24, 0x42, 0x93, 0xf6, 0xbf, 0x26, 0x8c, 0xcf,
	0x16, 0xc9, 0xa5, 0xb7, 0x78, 0x8f, 0x9f, 0x28, 0xf4, 0xf5, 0x1c, 0x20, 0xbc, 0x54, 0x87, 0xa1,
	0x3f, 0xcb, 0xb5, 0x1c, 0xfd, 0x29, 0x10, 0x84, 0x66, 0x47, 0xd0, 0x8f, 0xc8, 0x26, 0x46, 0xe7,
	0x96, 0x3b, 0x70, 0xe8, 0x7a, 0x16, 0x86, 0x84, 0xbd, 0x85, 0xbd, 0xa8, 0xba, 0xcf, 0xb0, 0x2a,
	0x96, 0xcb, 0x9c, 0xad, 0x4d, 0x27, 0xb6, 0xc5, 0x72, 0xf9, 0xa5, 0xd4, 0x31, 0x56, 0x4d, 0x2e,
	0x3f, 0xa3, 0x0e, 0xc2, 0x14, 0xb1, 0xd7, 0x30, 0x8a, 0xcd, 0x41, 0xc1, 0x6a, 0x5a, 0xee, 0xd8,
	0xa9, 0x0c, 0x90, 0xa8, 0x0a, 0xd9, 0x0c, 0xf6, 0xe3, 0x9a, 0x86, 0xc2, 0xc5, 0x65, 0xb9, 0x77,
	0x9c, 0xba, 0x6e, 0x13, 0xb5, 0x8f, 0xfc, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x7c, 0x47, 0x2a,
	0x20, 0x08, 0x00, 0x00,
}
