// Code generated by protoc-gen-go.
// source: src/protos/gate/gate.proto
// DO NOT EDIT!

/*
Package gate is a generated protocol buffer package.

It is generated from these files:
	src/protos/gate/gate.proto

It has these top-level messages:
	Gate_PingC2S
	Gate_PingS2C
*/
package gate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Gate_PingC2S struct {
	Content          *string `protobuf:"bytes,1,req,name=Content,json=content" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Gate_PingC2S) Reset()                    { *m = Gate_PingC2S{} }
func (m *Gate_PingC2S) String() string            { return proto.CompactTextString(m) }
func (*Gate_PingC2S) ProtoMessage()               {}
func (*Gate_PingC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Gate_PingC2S) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type Gate_PingS2C struct {
	Content          *string `protobuf:"bytes,1,req,name=Content,json=content" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Gate_PingS2C) Reset()                    { *m = Gate_PingS2C{} }
func (m *Gate_PingS2C) String() string            { return proto.CompactTextString(m) }
func (*Gate_PingS2C) ProtoMessage()               {}
func (*Gate_PingS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Gate_PingS2C) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Gate_PingC2S)(nil), "Gate_PingC2S")
	proto.RegisterType((*Gate_PingS2C)(nil), "Gate_PingS2C")
}

var fileDescriptor0 = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x2e, 0x4a, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0xd6, 0x4f, 0x4f, 0x2c, 0x49, 0x05, 0x13, 0x7a, 0x60, 0x01,
	0x25, 0x0d, 0x2e, 0x1e, 0x77, 0x20, 0x2f, 0x3e, 0x20, 0x33, 0x2f, 0xdd, 0xd9, 0x28, 0x58, 0x48,
	0x82, 0x8b, 0xdd, 0x39, 0x3f, 0xaf, 0x24, 0x35, 0xaf, 0x44, 0x82, 0x51, 0x81, 0x49, 0x83, 0x33,
	0x88, 0x3d, 0x19, 0xc2, 0x45, 0x51, 0x19, 0x6c, 0xe4, 0x8c, 0x5b, 0x25, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xa1, 0xa3, 0xb6, 0x7d, 0x70, 0x00, 0x00, 0x00,
}
