// Code generated by protoc-gen-go.
// source: src/protos/admin/admin.proto
// DO NOT EDIT!

/*
Package admin is a generated protocol buffer package.

It is generated from these files:
	src/protos/admin/admin.proto

It has these top-level messages:
	Admin_PingC2S
	Admin_PingS2C
	Admin_UserLoginC2S
	Admin_UserLoginS2C
	Admin_UserRegisterC2S
	Admin_UserRegisterS2C
	Admin_UserExitC2S
	Admin_UserExitS2C
*/
package admin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Admin_PingC2S struct {
	Content          *string `protobuf:"bytes,1,req,name=Content,json=content" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Admin_PingC2S) Reset()                    { *m = Admin_PingC2S{} }
func (m *Admin_PingC2S) String() string            { return proto.CompactTextString(m) }
func (*Admin_PingC2S) ProtoMessage()               {}
func (*Admin_PingC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Admin_PingC2S) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type Admin_PingS2C struct {
	Content          *string `protobuf:"bytes,1,req,name=Content,json=content" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Admin_PingS2C) Reset()                    { *m = Admin_PingS2C{} }
func (m *Admin_PingS2C) String() string            { return proto.CompactTextString(m) }
func (*Admin_PingS2C) ProtoMessage()               {}
func (*Admin_PingS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Admin_PingS2C) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type Admin_UserLoginC2S struct {
	Name             *string `protobuf:"bytes,1,req,name=Name,json=name" json:"Name,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=Password,json=password" json:"Password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Admin_UserLoginC2S) Reset()                    { *m = Admin_UserLoginC2S{} }
func (m *Admin_UserLoginC2S) String() string            { return proto.CompactTextString(m) }
func (*Admin_UserLoginC2S) ProtoMessage()               {}
func (*Admin_UserLoginC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Admin_UserLoginC2S) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Admin_UserLoginC2S) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type Admin_UserLoginS2C struct {
	UserID           *uint64 `protobuf:"varint,1,opt,name=UserID,json=userID" json:"UserID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Admin_UserLoginS2C) Reset()                    { *m = Admin_UserLoginS2C{} }
func (m *Admin_UserLoginS2C) String() string            { return proto.CompactTextString(m) }
func (*Admin_UserLoginS2C) ProtoMessage()               {}
func (*Admin_UserLoginS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Admin_UserLoginS2C) GetUserID() uint64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

type Admin_UserRegisterC2S struct {
	Name             *string `protobuf:"bytes,1,req,name=Name,json=name" json:"Name,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=Password,json=password" json:"Password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Admin_UserRegisterC2S) Reset()                    { *m = Admin_UserRegisterC2S{} }
func (m *Admin_UserRegisterC2S) String() string            { return proto.CompactTextString(m) }
func (*Admin_UserRegisterC2S) ProtoMessage()               {}
func (*Admin_UserRegisterC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Admin_UserRegisterC2S) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Admin_UserRegisterC2S) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type Admin_UserRegisterS2C struct {
	UserID           *uint64 `protobuf:"varint,1,opt,name=UserID,json=userID" json:"UserID,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Admin_UserRegisterS2C) Reset()                    { *m = Admin_UserRegisterS2C{} }
func (m *Admin_UserRegisterS2C) String() string            { return proto.CompactTextString(m) }
func (*Admin_UserRegisterS2C) ProtoMessage()               {}
func (*Admin_UserRegisterS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Admin_UserRegisterS2C) GetUserID() uint64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Admin_UserRegisterS2C) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type Admin_UserExitC2S struct {
	Optional_UserID  *uint64 `protobuf:"varint,1,opt,name=Optional_UserID,json=optionalUserID" json:"Optional_UserID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Admin_UserExitC2S) Reset()                    { *m = Admin_UserExitC2S{} }
func (m *Admin_UserExitC2S) String() string            { return proto.CompactTextString(m) }
func (*Admin_UserExitC2S) ProtoMessage()               {}
func (*Admin_UserExitC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Admin_UserExitC2S) GetOptional_UserID() uint64 {
	if m != nil && m.Optional_UserID != nil {
		return *m.Optional_UserID
	}
	return 0
}

type Admin_UserExitS2C struct {
	Result           *bool  `protobuf:"varint,1,req,name=Result,json=result" json:"Result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Admin_UserExitS2C) Reset()                    { *m = Admin_UserExitS2C{} }
func (m *Admin_UserExitS2C) String() string            { return proto.CompactTextString(m) }
func (*Admin_UserExitS2C) ProtoMessage()               {}
func (*Admin_UserExitS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Admin_UserExitS2C) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*Admin_PingC2S)(nil), "Admin_PingC2S")
	proto.RegisterType((*Admin_PingS2C)(nil), "Admin_PingS2C")
	proto.RegisterType((*Admin_UserLoginC2S)(nil), "Admin_UserLoginC2S")
	proto.RegisterType((*Admin_UserLoginS2C)(nil), "Admin_UserLoginS2C")
	proto.RegisterType((*Admin_UserRegisterC2S)(nil), "Admin_UserRegisterC2S")
	proto.RegisterType((*Admin_UserRegisterS2C)(nil), "Admin_UserRegisterS2C")
	proto.RegisterType((*Admin_UserExitC2S)(nil), "Admin_UserExitC2S")
	proto.RegisterType((*Admin_UserExitS2C)(nil), "Admin_UserExitS2C")
}

var fileDescriptor0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x2e, 0x4a, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0xd6, 0x4f, 0x4c, 0xc9, 0xcd, 0xcc, 0x83, 0x90, 0x7a, 0x60,
	0x21, 0x25, 0x4d, 0x2e, 0x5e, 0x47, 0x10, 0x37, 0x3e, 0x20, 0x33, 0x2f, 0xdd, 0xd9, 0x28, 0x58,
	0x48, 0x82, 0x8b, 0xdd, 0x39, 0x3f, 0xaf, 0x24, 0x35, 0xaf, 0x44, 0x82, 0x51, 0x81, 0x49, 0x83,
	0x33, 0x88, 0x3d, 0x19, 0xc2, 0x45, 0x55, 0x1a, 0x6c, 0xe4, 0x8c, 0x47, 0xa9, 0x0b, 0x97, 0x10,
	0x44, 0x69, 0x68, 0x71, 0x6a, 0x91, 0x4f, 0x7e, 0x7a, 0x66, 0x1e, 0xc8, 0x68, 0x21, 0x2e, 0x16,
	0xbf, 0xc4, 0xdc, 0x54, 0xa8, 0x62, 0x96, 0x3c, 0x20, 0x5b, 0x48, 0x8a, 0x8b, 0x23, 0x20, 0xb1,
	0xb8, 0xb8, 0x3c, 0xbf, 0x28, 0x45, 0x82, 0x09, 0x2c, 0xce, 0x51, 0x00, 0xe5, 0x2b, 0xe9, 0x60,
	0x98, 0x02, 0xb2, 0x55, 0x8c, 0x8b, 0x0d, 0xc4, 0xf7, 0x74, 0x01, 0x9a, 0xc3, 0xa8, 0xc1, 0x12,
	0xc4, 0x56, 0x0a, 0xe6, 0x29, 0xb9, 0x73, 0x89, 0x22, 0x54, 0x07, 0xa5, 0xa6, 0x67, 0x16, 0x97,
	0xa4, 0x16, 0x91, 0x63, 0xad, 0x33, 0x36, 0x83, 0xf0, 0xd8, 0x0c, 0xb7, 0x80, 0x09, 0x28, 0x0a,
	0xb5, 0x40, 0xc9, 0x86, 0x4b, 0x10, 0x61, 0x88, 0x6b, 0x45, 0x66, 0x09, 0xc8, 0x25, 0xea, 0x5c,
	0xfc, 0xfe, 0x05, 0x25, 0x99, 0xf9, 0x79, 0x89, 0x39, 0xf1, 0x28, 0x26, 0xf1, 0xe5, 0x43, 0x85,
	0x21, 0xa2, 0x4a, 0xda, 0xe8, 0xba, 0xa1, 0xd6, 0x07, 0xa5, 0x16, 0x97, 0xe6, 0x40, 0x42, 0x9b,
	0x23, 0x88, 0xad, 0x08, 0xcc, 0x03, 0x04, 0x00, 0x00, 0xff, 0xff, 0xae, 0x89, 0xd4, 0xe7, 0xe1,
	0x01, 0x00, 0x00,
}
